#

## Business Understanding

### Background
Climate change and the global transition toward cleaner energy have increased pressure on governments, businesses, and investors to reduce carbon dioxide (CO₂) emissions. However, countries differ significantly in their emissions levels, economic activity, population, energy consumption, carbon intensity, and dependence on fossil fuels.

These differences make it difficult to apply the same clean-energy strategy across all countries. Grouping countries according to similar environmental, economic, demographic, and energy characteristics can help decision-makers better understand different country profiles and identify where particular clean-energy solutions and interventions may be most relevant.
Using historical country-level data on CO₂ emissions, GDP, population, energy consumption, and emission sources provides an opportunity to identify meaningful patterns and similarities among countries through data-driven analysis.

### Business Problem
Businesses, investors, and policymakers face challenges in identifying and comparing countries with similar clean-energy needs. Relying only on total CO₂ emissions may overlook important differences in economic activity, population, energy consumption, carbon intensity, and sources of emissions.
Without a systematic way of grouping countries according to these characteristics, decision-makers may struggle to identify markets with similar environmental challenges and determine which groups of countries should receive greater attention for clean-energy solutions and emission-reduction interventions.

### Business Objective
The objective of this project is to use country-level CO₂ emissions, economic, demographic, and energy data to identify groups of countries with similar characteristics.
By developing country profiles through clustering, the project aims to help businesses, investors, policymakers, and development organizations better understand differences between markets and identify groups that may require different clean-energy strategies or levels of intervention.

## Data Understanding

The dataset comes

In [185]:
# Importing the neccesary libraries
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [186]:
# Loading the dataset
df = pd.read_csv('owid-co2-data.csv')
df.head()

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,co2_including_luc_growth_abs,co2_including_luc_growth_prct,co2_including_luc_per_capita,co2_including_luc_per_gdp,co2_including_luc_per_unit_energy,co2_per_capita,co2_per_gdp,co2_per_unit_energy,coal_co2,coal_co2_per_capita,consumption_co2,consumption_co2_per_capita,consumption_co2_per_gdp,cumulative_cement_co2,cumulative_co2,cumulative_co2_including_luc,cumulative_coal_co2,cumulative_flaring_co2,cumulative_gas_co2,cumulative_luc_co2,cumulative_oil_co2,cumulative_other_co2,energy_per_capita,energy_per_gdp,flaring_co2,flaring_co2_per_capita,gas_co2,gas_co2_per_capita,ghg_excluding_lucf_per_capita,ghg_per_capita,land_use_change_co2,land_use_change_co2_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,oil_co2,oil_co2_per_capita,other_co2_per_capita,other_industry_co2,primary_energy_consumption,share_global_cement_co2,share_global_co2,share_global_co2_including_luc,share_global_coal_co2,share_global_cumulative_cement_co2,share_global_cumulative_co2,share_global_cumulative_co2_including_luc,share_global_cumulative_coal_co2,share_global_cumulative_flaring_co2,share_global_cumulative_gas_co2,share_global_cumulative_luc_co2,share_global_cumulative_oil_co2,share_global_cumulative_other_co2,share_global_flaring_co2,share_global_gas_co2,share_global_luc_co2,share_global_oil_co2,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1750,AFG,2802560.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1751,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1752,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1753,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1754,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [187]:
# Checking the shape
df.shape

(50411, 79)

This dataset contains **50411** rows and **79** columns

In [188]:
# Checking the information of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50411 entries, 0 to 50410
Data columns (total 79 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   country                                    50411 non-null  object
 1   year                                       50411 non-null  int64
 2   iso_code                                   42480 non-null  object
 3   population                                 41167 non-null  float64
 4   gdp                                        15251 non-null  float64
 5   cement_co2                                 29173 non-null  float64
 6   cement_co2_per_capita                      25648 non-null  float64
 7   co2                                        29384 non-null  float64
 8   co2_growth_abs                             27216 non-null  float64
 9   co2_growth_prct                            26239 non-null  float64
 10  co2_including_luc                          23796 non-null  float64
 11  co2_including_luc_growth_abs               23496 non-null  float64
 12  co2_including_luc_growth_prct              23496 non-null  float64
 13  co2_including_luc_per_capita               23757 non-null  float64
 14  co2_including_luc_per_gdp                  16790 non-null  float64
 15  co2_including_luc_per_unit_energy          10133 non-null  float64
 16  co2_per_capita                             26509 non-null  float64
 17  co2_per_gdp                                17528 non-null  float64
 18  co2_per_unit_energy                        10826 non-null  float64
 19  coal_co2                                   21925 non-null  float64
 20  coal_co2_per_capita                        21314 non-null  float64
 21  consumption_co2                            5053 non-null   float64
 22  consumption_co2_per_capita                 4643 non-null   float64
 23  consumption_co2_per_gdp                    4448 non-null   float64
 24  cumulative_cement_co2                      29151 non-null  float64
 25  cumulative_co2                             27563 non-null  float64
 26  cumulative_co2_including_luc               23796 non-null  float64
 27  cumulative_coal_co2                        21925 non-null  float64
 28  cumulative_flaring_co2                     16111 non-null  float64
 29  cumulative_gas_co2                         18147 non-null  float64
 30  cumulative_luc_co2                         37450 non-null  float64
 31  cumulative_oil_co2                         25458 non-null  float64
 32  cumulative_other_co2                       3254 non-null   float64
 33  energy_per_capita                          10586 non-null  float64
 34  energy_per_gdp                             7787 non-null   float64
 35  flaring_co2                                16174 non-null  float64
 36  flaring_co2_per_capita                     14910 non-null  float64
 37  gas_co2                                    18147 non-null  float64
 38  gas_co2_per_capita                         17446 non-null  float64
 39  ghg_excluding_lucf_per_capita              35842 non-null  float64
 40  ghg_per_capita                             36179 non-null  float64
 41  land_use_change_co2                        37450 non-null  float64
 42  land_use_change_co2_per_capita             36635 non-null  float64
 43  methane                                    38150 non-null  float64
 44  methane_per_capita                         36179 non-null  float64
 45  nitrous_oxide                              38500 non-null  float64
 46  nitrous_oxide_per_capita                   36439 non-null  float64
 47  oil_co2                                    25459 non-null  float64
 48  oil_co2_per_capita                         24722 non-null  float64
 49  other_co2_per_capita                       2659 non-null   float64
 50  other_industry_co2                         3254 non-null   float64
 51  primary_energy_consumption                 10631 non-null  float64
 52  share_global_cement_co2                    22270 non-null  float64
 53  share_global_co2                           27563 non-null  float64
 54  share_global_co2_including_luc             23796 non-null  float64
 55  share_global_coal_co2                      21925 non-null  float64
 56  share_global_cumulative_cement_co2         22270 non-null  float64
 57  share_global_cumulative_co2                27563 non-null  float64
 58  share_global_cumulative_co2_including_luc  23796 non-null  float64
 59  share_global_cumulative_coal_co2           21925 non-null  float64
 60  share_global_cumulative_flaring_co2        11089 non-null  float64
 61  share_global_cumulative_gas_co2            15167 non-null  float64
 62  share_global_cumulative_luc_co2            37450 non-null  float64
 63  share_global_cumulative_oil_co2            23833 non-null  float64
 64  share_global_cumulative_other_co2          2170 non-null   float64
 65  share_global_flaring_co2                   11089 non-null  float64
 66  share_global_gas_co2                       15167 non-null  float64
 67  share_global_luc_co2                       37450 non-null  float64
 68  share_global_oil_co2                       23833 non-null  float64
 69  share_global_other_co2                     2170 non-null   float64
 70  share_of_temperature_change_from_ghg       41238 non-null  float64
 71  temperature_change_from_ch4                38280 non-null  float64
 72  temperature_change_from_co2                41238 non-null  float64
 73  temperature_change_from_ghg                41238 non-null  float64
 74  temperature_change_from_n2o                38280 non-null  float64
 75  total_ghg                                  38150 non-null  float64
 76  total_ghg_excluding_lucf                   37813 non-null  float64
 77  trade_co2                                  4712 non-null   float64
 78  trade_co2_share                            4712 non-null   float64
dtypes: float64(76), int64(1), object(2)
memory usage: 30.4+ MB

It looks like there are missing data in the dataset.

In [189]:
# Checking for missing data
missing_summary = pd.DataFrame({
    'Missing Count': df.isna().sum(),
    'Missing Percent': df.isna().mean() * 100
})

missing_summary['Combined'] = (
    missing_summary['Missing Count'].astype(str)
    + " ("
    + missing_summary['Missing Percent'].round(2).astype(str)
    + "%)"
)

missing_summary.round(2)

,Missing Count,Missing Percent,Combined
country,0,0.00,0 (0.0%)
year,0,0.00,0 (0.0%)
iso_code,7931,15.73,7931 (15.73%)
population,9244,18.34,9244 (18.34%)
gdp,35160,69.75,35160 (69.75%)
cement_co2,21238,42.13,21238 (42.13%)
cement_co2_per_capita,24763,49.12,24763 (49.12%)
co2,21027,41.71,21027 (41.71%)
co2_growth_abs,23195,46.01,23195 (46.01%)
co2_growth_prct,24172,47.95,24172 (47.95%)
co2_including_luc,26615,52.80,26615 (52.8%)
co2_including_luc_growth_abs,26915,53.39,26915 (53.39%)
co2_including_luc_growth_prct,26915,53.39,26915 (53.39%)
co2_including_luc_per_capita,26654,52.87,26654 (52.87%)
co2_including_luc_per_gdp,33621,66.69,33621 (66.69%)
co2_including_luc_per_unit_energy,40278,79.90,40278 (79.9%)
co2_per_capita,23902,47.41,23902 (47.41%)
co2_per_gdp,32883,65.23,32883 (65.23%)
co2_per_unit_energy,39585,78.52,39585 (78.52%)
coal_co2,28486,56.51,28486 (56.51%)
coal_co2_per_capita,29097,57.72,29097 (57.72%)
consumption_co2,45358,89.98,45358 (89.98%)
consumption_co2_per_capita,45768,90.79,45768 (90.79%)
consumption_co2_per_gdp,45963,91.18,45963 (91.18%)
cumulative_cement_co2,21260,42.17,21260 (42.17%)
cumulative_co2,22848,45.32,22848 (45.32%)
cumulative_co2_including_luc,26615,52.80,26615 (52.8%)
cumulative_coal_co2,28486,56.51,28486 (56.51%)
cumulative_flaring_co2,34300,68.04,34300 (68.04%)
cumulative_gas_co2,32264,64.00,32264 (64.0%)
cumulative_luc_co2,12961,25.71,12961 (25.71%)
cumulative_oil_co2,24953,49.50,24953 (49.5%)
cumulative_other_co2,47157,93.55,47157 (93.55%)
energy_per_capita,39825,79.00,39825 (79.0%)
energy_per_gdp,42624,84.55,42624 (84.55%)
flaring_co2,34237,67.92,34237 (67.92%)
flaring_co2_per_capita,35501,70.42,35501 (70.42%)
gas_co2,32264,64.00,32264 (64.0%)
gas_co2_per_capita,32965,65.39,32965 (65.39%)
ghg_excluding_lucf_per_capita,14569,28.90,14569 (28.9%)
ghg_per_capita,14232,28.23,14232 (28.23%)
land_use_change_co2,12961,25.71,12961 (25.71%)
land_use_change_co2_per_capita,13776,27.33,13776 (27.33%)
methane,12261,24.32,12261 (24.32%)
methane_per_capita,14232,28.23,14232 (28.23%)
nitrous_oxide,11911,23.63,11911 (23.63%)
nitrous_oxide_per_capita,13972,27.72,13972 (27.72%)
oil_co2,24952,49.50,24952 (49.5%)
oil_co2_per_capita,25689,50.96,25689 (50.96%)
other_co2_per_capita,47752,94.73,47752 (94.73%)
other_industry_co2,47157,93.55,47157 (93.55%)
primary_energy_consumption,39780,78.91,39780 (78.91%)
share_global_cement_co2,28141,55.82,28141 (55.82%)
share_global_co2,22848,45.32,22848 (45.32%)
share_global_co2_including_luc,26615,52.80,26615 (52.8%)
share_global_coal_co2,28486,56.51,28486 (56.51%)
share_global_cumulative_cement_co2,28141,55.82,28141 (55.82%)
share_global_cumulative_co2,22848,45.32,22848 (45.32%)
share_global_cumulative_co2_including_luc,26615,52.80,26615 (52.8%)
share_global_cumulative_coal_co2,28486,56.51,28486 (56.51%)
share_global_cumulative_flaring_co2,39322,78.00,39322 (78.0%)
share_global_cumulative_gas_co2,35244,69.91,35244 (69.91%)
share_global_cumulative_luc_co2,12961,25.71,12961 (25.71%)
share_global_cumulative_oil_co2,26578,52.72,26578 (52.72%)
share_global_cumulative_other_co2,48241,95.70,48241 (95.7%)
share_global_flaring_co2,39322,78.00,39322 (78.0%)
share_global_gas_co2,35244,69.91,35244 (69.91%)
share_global_luc_co2,12961,25.71,12961 (25.71%)
share_global_oil_co2,26578,52.72,26578 (52.72%)
share_global_other_co2,48241,95.70,48241 (95.7%)
share_of_temperature_change_from_ghg,9173,18.20,9173 (18.2%)
temperature_change_from_ch4,12131,24.06,12131 (24.06%)
temperature_change_from_co2,9173,18.20,9173 (18.2%)
temperature_change_from_ghg,9173,18.20,9173 (18.2%)
temperature_change_from_n2o,12131,24.06,12131 (24.06%)
total_ghg,12261,24.32,12261 (24.32%)
total_ghg_excluding_lucf,12598,24.99,12598 (24.99%)
trade_co2,45699,90.65,45699 (90.65%)
trade_co2_share,45699,90.65,45699 (90.65%)

The above are the number of missing data and their percentage of every column in the dataset.

In cleaning of this dataset, we have to be careful in how we will clean it.

In [190]:
# Checking the column names
df.columns

Index(['country', 'year', 'iso_code', 'population', 'gdp', 'cement_co2',
       'cement_co2_per_capita', 'co2', 'co2_growth_abs', 'co2_growth_prct',
       'co2_including_luc', 'co2_including_luc_growth_abs',
       'co2_including_luc_growth_prct', 'co2_including_luc_per_capita',
       'co2_including_luc_per_gdp', 'co2_including_luc_per_unit_energy',
       'co2_per_capita', 'co2_per_gdp', 'co2_per_unit_energy', 'coal_co2',
       'coal_co2_per_capita', 'consumption_co2', 'consumption_co2_per_capita',
       'consumption_co2_per_gdp', 'cumulative_cement_co2', 'cumulative_co2',
       'cumulative_co2_including_luc', 'cumulative_coal_co2',
       'cumulative_flaring_co2', 'cumulative_gas_co2', 'cumulative_luc_co2',
       'cumulative_oil_co2', 'cumulative_other_co2', 'energy_per_capita',
       'energy_per_gdp', 'flaring_co2', 'flaring_co2_per_capita', 'gas_co2',
       'gas_co2_per_capita', 'ghg_excluding_lucf_per_capita', 'ghg_per_capita',
       'land_use_change_co2', 'land_use_change_co2_per_capita', 'methane',
       'methane_per_capita', 'nitrous_oxide', 'nitrous_oxide_per_capita',
       'oil_co2', 'oil_co2_per_capita', 'other_co2_per_capita',
       'other_industry_co2', 'primary_energy_consumption',
       'share_global_cement_co2', 'share_global_co2',
       'share_global_co2_including_luc', 'share_global_coal_co2',
       'share_global_cumulative_cement_co2', 'share_global_cumulative_co2',
       'share_global_cumulative_co2_including_luc',
       'share_global_cumulative_coal_co2',
       'share_global_cumulative_flaring_co2',
       'share_global_cumulative_gas_co2', 'share_global_cumulative_luc_co2',
       'share_global_cumulative_oil_co2', 'share_global_cumulative_other_co2',
       'share_global_flaring_co2', 'share_global_gas_co2',
       'share_global_luc_co2', 'share_global_oil_co2',
       'share_global_other_co2', 'share_of_temperature_change_from_ghg',
       'temperature_change_from_ch4', 'temperature_change_from_co2',
       'temperature_change_from_ghg', 'temperature_change_from_n2o',
       'total_ghg', 'total_ghg_excluding_lucf', 'trade_co2',
       'trade_co2_share'],
      dtype='object')

The above is all the names of the columns in this dataset.

In [191]:
# Checking the decsription of the dataset
describe = df.describe()

describe

,year,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,co2_including_luc_growth_abs,co2_including_luc_growth_prct,co2_including_luc_per_capita,co2_including_luc_per_gdp,co2_including_luc_per_unit_energy,co2_per_capita,co2_per_gdp,co2_per_unit_energy,coal_co2,coal_co2_per_capita,consumption_co2,consumption_co2_per_capita,consumption_co2_per_gdp,cumulative_cement_co2,cumulative_co2,cumulative_co2_including_luc,cumulative_coal_co2,cumulative_flaring_co2,cumulative_gas_co2,cumulative_luc_co2,cumulative_oil_co2,cumulative_other_co2,energy_per_capita,energy_per_gdp,flaring_co2,flaring_co2_per_capita,gas_co2,gas_co2_per_capita,ghg_excluding_lucf_per_capita,ghg_per_capita,land_use_change_co2,land_use_change_co2_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,oil_co2,oil_co2_per_capita,other_co2_per_capita,other_industry_co2,primary_energy_consumption,share_global_cement_co2,share_global_co2,share_global_co2_including_luc,share_global_coal_co2,share_global_cumulative_cement_co2,share_global_cumulative_co2,share_global_cumulative_co2_including_luc,share_global_cumulative_coal_co2,share_global_cumulative_flaring_co2,share_global_cumulative_gas_co2,share_global_cumulative_luc_co2,share_global_cumulative_oil_co2,share_global_cumulative_other_co2,share_global_flaring_co2,share_global_gas_co2,share_global_luc_co2,share_global_oil_co2,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
count,50411.000000,4.116700e+04,1.525100e+04,29173.000000,25648.000000,29384.000000,27216.000000,26239.000000,23796.000000,23496.000000,23496.000000,23757.000000,16790.000000,10133.000000,26509.000000,17528.000000,10826.000000,21925.000000,21314.000000,5053.000000,4643.000000,4448.000000,29151.000000,2.756300e+04,2.379600e+04,21925.000000,16111.000000,18147.000000,37450.000000,25458.000000,3254.000000,10586.000000,7787.000000,16174.000000,14910.000000,18147.000000,17446.000000,35842.00000,36179.000000,37450.000000,36635.000000,38150.000000,36179.000000,38500.000000,36439.000000,25459.000000,24722.000000,2659.000000,3254.000000,10631.000000,22270.000000,27563.000000,23796.000000,21925.000000,22270.000000,27563.000000,23796.000000,21925.000000,11089.000000,15167.000000,37450.000000,23833.000000,2170.000000,11089.000000,15167.000000,37450.000000,23833.000000,2170.000000,41238.000000,38280.000000,41238.000000,41238.000000,38280.000000,38150.000000,37813.000000,4712.000000,4712.000000
mean,1920.349249,6.017294e+07,3.300495e+11,7.890109,0.060026,420.227035,6.268847,42.598225,544.144592,7.483698,4.132343,7.115447,2.328426,1343.224898,3.821411,0.397679,251.177589,185.496070,1.285324,1318.129607,6.463631,0.349924,196.486344,1.249223e+04,2.790247e+04,9311.023979,177.231149,1876.820098,9998.375654,3777.605153,417.861562,24218.017776,1.672906,5.854644,0.270544,74.840369,0.797032,3.07991,7.716833,124.752927,3.905510,95.277707,1.741468,25.424751,0.444591,115.307630,2.192718,0.082205,20.116569,2450.931544,3.002813,5.369860,3.457512,6.791725,2.995657,5.500642,3.321957,6.974350,3.043673,4.104541,2.559362,3.351795,7.053671,3.126383,4.195698,2.439717,3.333339,7.190616,2.272236,0.002871,0.008014,0.011224,0.000509,490.799608,310.521459,-6.986781,21.468641
std,65.859123,3.308412e+08,3.086383e+12,62.988171,0.123566,1972.092032,62.199548,1721.913018,2273.281696,99.512520,166.964358,8.921137,5.626872,6678.225759,14.312856,0.754065,315.226128,855.418419,2.351089,3904.104954,6.852299,0.247281,1495.918343,7.312143e+04,1.269563e+05,43499.981365,926.732659,11756.922691,46043.141427,24886.829185,1317.317547,32203.518384,1.629769,26.749898,2.995049,397.296985,2.805144,7.78545,11.276765,519.818810,9.106597,434.707032,3.832696,129.896895,0.799286,646.556645,13.948769,0.079726,55.644708,11383.276535,13.389959,18.734892,11.709725,20.969463,13.459332,19.503609,11.675183,21.797169,11.239887,17.155976,9.773304,13.260472,17.554077,11.147780,16.683568,9.800818,13.031193,17.448980,9.282343,0.015362,0.045687,0.062888,0.003048,2414.076755,1812.363570,259.018184,62.637598
min,1750.000000,2.150000e+02,4.998000e+07,0.000000,0.000000,0.000000,-1928.339000,-100.000000,-84.560000,-2298.978000,-11927.241000,-12.455000,-12.938000,-8673.521000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,-1.203450e+02,0.000000,0.000000,0.000000,-3918.006000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.02200,-28.852000,-319.418000,-45.317000,0.000000,0.032000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.375000,0.000000,0.000000,0.000000,-0.101000,0.000000,0.000000,0.000000,-0.518000,0.000000,0.000000,0.000000,0.000000,-6.966000,0.000000,0.000000,-0.824000,-0.001000,0.000000,-0.001000,0.000000,-19.725000,0.000000,-2177.807000,-98.281000
25%,1875.000000,3.272140e+05,7.874038e+09,0.000000,0.000000,0.381000,-0.005000,-1.070500,6.667750,-0.727500,-3.784500,2.058000,0.398000,202.796000,0.171000,0.131750,187.012250,0.068000,0.017000,12.079000,1.127500,0.208000,0.000000,4.238000e+00,1.836610e+02,1.549000,0.000000,0.000000,12.678500,0.909000,0.266000,2703.230500,0.770000,0.000000,0.000000,0.000000,0.000000,0.28100,1.944000,0.024000,0.121000,0.389000,0.615000,0.071000,0.109000,0.088000,0.048000,0.023500,0.013000,6.779500,0.000000,0.004000,0.041000,0.002000,0.000000,0.002000,0.027000,0.002000,0.000000,0.000000,0.008000,0.004000,0.127000,0.000000,0.000000,0.001000,0.006000,0.144000,0.003000,0.000000,0.000000,0.000000,0.000000,1.502000,0.221000,-2.262250,-6.828750
50%,1925.000000,2.291264e+06,2.743861e+10,0.000000,0.001000,5.081000,0.044000,3.813000,28.120000,0.112000,1.183000,4.536000,0.878000,282.230000,1.023000,0.264000,220.868500,2.096000,0.227000,74.336000,4.323000,0.301000,0.000000,8.046600e+01,1.039956e+03,57.155000,0.000000,0.189000,282.849500,24.131000,21.406500,11792.955000,1.245000,0.000000,0.000000,0.018000,0.004000,0.66050,4.278000,3.396500,1.306000,3.462500,1.006000,0.706000,0.224000,1.398000,0.404000,0.065000,1.321500,58.186000,0.026500,0.053000,0.176000,0.058000,0.021000,0.029000,0.144000,0.040000,0.004000,0.014000,0.105000,0.057000,0.431500,0.001000,0.026000,0.072000,0.067000,0.588500,0.081000,0.000000,0.000000,0.000000,0.000000,14.605500,2.222000,1.641000,8.381500
75%,1975.000000,9.986553e+06,1.212627e+11,0.524000,0.077000,53.656500,1.018000,10.884000,124.303250,2.765250,6.092000,9.113000,2.151000,810.833000,4.327000,0.509000,260.702250,27.857000,1.583000,454.813000,9.791500,0.428000,9.816500,1.163684e+03,5.151784e+03,915.739000,6.169000,88.334000,1758.260000,312.618250,131.841500,35225.447500,2.053500,0.337000,0.031000,6.606500,0.453750,2.83200,9.235000,23.189250,4.258000,18.546750,1.692000,5.150000,0.457000,14.412500,2.012750,0.115000,6.403000,450.072000,0.365750,0.575000,0.838000,0.919000,0.345750,0.401500,0.688000,0.672000,0.479000,0.322000,0.509000,0.509000,2.142250,0.669000,0.500500,0.486000,0.544000,2.416500,0.373000,0.000000,0.001000,0.002000,0.000000,76.508500,27.863000,11.425500,32.782250
max,2024.000000,8.161973e+09,1.301126e+14,1666.885000,2.484000,38598.578000,1804.657000,180870.000000,43184.086000,2614.874000,6362.499000,364.809000,291.293000,511469.312000,782.743000,82.599000,10688.897000,15805.254000,34.295000,38598.578000,63.272000,3.306000,49693.922000,1.849124e+06,2.751504e+06,849832.250000,20141.375000,276572.688000,906953.562000,638014.188000,14869.403000,318559.688000,25.253000,432.392000,114.509000,8009.828000,53.476000,369.65000,369.705000,8692.767000,305.195000,9498.914000,133.104000,2935.779000,20.393000,12470.596000,782.743000,0.604000,458.178000,176737.094000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,0.377000,1.216000,1.678000,0.085000,54433.398000,43714.777000,1768.846000,1023.042000

In [192]:
df['trade_co2_share']

0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
5             NaN
6             NaN
7             NaN
8             NaN
9             NaN
10            NaN
11            NaN
12            NaN
13            NaN
14            NaN
15            NaN
16            NaN
17            NaN
18            NaN
19            NaN
20            NaN
21            NaN
22            NaN
23            NaN
24            NaN
25            NaN
26            NaN
27            NaN
28            NaN
29            NaN
30            NaN
31            NaN
32            NaN
33            NaN
34            NaN
35            NaN
36            NaN
37            NaN
38            NaN
39            NaN
40            NaN
41            NaN
42            NaN
43            NaN
44            NaN
45            NaN
46            NaN
47            NaN
48            NaN
49            NaN
50            NaN
51            NaN
52            NaN
53            NaN
54            NaN
55            NaN
56            NaN
57            NaN
58            NaN
59            NaN
60            NaN
61            NaN
62            NaN
63            NaN
64            NaN
65            NaN
66            NaN
67            NaN
68            NaN
69            NaN
70            NaN
71            NaN
72            NaN
73            NaN
74            NaN
75            NaN
76            NaN
77            NaN
78            NaN
79            NaN
80            NaN
81            NaN
82            NaN
83            NaN
84            NaN
85            NaN
86            NaN
87            NaN
88            NaN
89            NaN
90            NaN
91            NaN
92            NaN
93            NaN
94            NaN
95            NaN
96            NaN
97            NaN
98            NaN
99            NaN
100           NaN
101           NaN
102           NaN
103           NaN
104           NaN
105           NaN
106           NaN
107           NaN
108           NaN
109           NaN
110           NaN
111           NaN
112           NaN
113           NaN
114           NaN
115           NaN
116           NaN
117           NaN
118           NaN
119           NaN
120           NaN
121           NaN
122           NaN
123           NaN
124           NaN
125           NaN
126           NaN
127           NaN
128           NaN
129           NaN
130           NaN
131           NaN
132           NaN
133           NaN
134           NaN
135           NaN
136           NaN
137           NaN
138           NaN
139           NaN
140           NaN
141           NaN
142           NaN
143           NaN
144           NaN
145           NaN
146           NaN
147           NaN
148           NaN
149           NaN
150           NaN
151           NaN
152           NaN
153           NaN
154           NaN
155           NaN
156           NaN
157           NaN
158           NaN
159           NaN
160           NaN
161           NaN
162           NaN
163           NaN
164           NaN
165           NaN
166           NaN
167           NaN
168           NaN
169           NaN
170           NaN
171           NaN
172           NaN
173           NaN
174           NaN
175           NaN
176           NaN
177           NaN
178           NaN
179           NaN
180           NaN
181           NaN
182           NaN
183           NaN
184           NaN
185           NaN
186           NaN
187           NaN
188           NaN
189           NaN
190           NaN
191           NaN
192           NaN
193           NaN
194           NaN
195           NaN
196           NaN
197           NaN
198           NaN
199           NaN
200           NaN
201           NaN
202           NaN
203           NaN
204           NaN
205           NaN
206           NaN
207           NaN
208           NaN
209           NaN
210           NaN
211           NaN
212           NaN
213           NaN
214           NaN
215           NaN
216           NaN
217           NaN
218           NaN
219           NaN
220           NaN
221           NaN
222           NaN
223           NaN
224           NaN
225           NaN
226           NaN
227           NaN
228           NaN
229           NaN
230           NaN
231           NaN
232           NaN
233           NaN
234           NaN
235           NaN
236           NaN
237           NaN
238           NaN
239           NaN
240           NaN
241           NaN
242           NaN
243           NaN
244           NaN
245           NaN
246           NaN
247           NaN
248           NaN
249           NaN
250           NaN
251           NaN
252           NaN
253           NaN
254           NaN
255           NaN
256           NaN
257           NaN
258           NaN
259           NaN
260           NaN
261           NaN
262           NaN
263           NaN
264           NaN
265           NaN
266           NaN
267           NaN
268           NaN
269           NaN
270           NaN
271           NaN
272           NaN
273           NaN
274           NaN
275           NaN
276           NaN
277           NaN
278           NaN
279           NaN
280           NaN
281           NaN
282           NaN
283           NaN
284           NaN
285           NaN
286           NaN
287           NaN
288           NaN
289           NaN
290           NaN
291           NaN
292           NaN
293           NaN
294           NaN
295           NaN
296           NaN
297           NaN
298           NaN
299           NaN
300           NaN
301           NaN
302           NaN
303           NaN
304           NaN
305           NaN
306           NaN
307           NaN
308           NaN
309           NaN
310           NaN
311           NaN
312           NaN
313           NaN
314           NaN
315           NaN
316           NaN
317           NaN
318           NaN
319           NaN
320           NaN
321           NaN
322           NaN
323           NaN
324           NaN
325           NaN
326           NaN
327           NaN
328           NaN
329           NaN
330           NaN
331           NaN
332           NaN
333           NaN
334           NaN
335           NaN
336           NaN
337           NaN
338           NaN
339           NaN
340           NaN
341           NaN
342           NaN
343           NaN
344           NaN
345           NaN
346           NaN
347           NaN
348           NaN
349           NaN
350           NaN
351           NaN
352           NaN
353           NaN
354           NaN
355           NaN
356           NaN
357           NaN
358           NaN
359           NaN
360           NaN
361           NaN
362           NaN
363           NaN
364           NaN
365           NaN
366           NaN
367           NaN
368           NaN
369           NaN
370           NaN
371           NaN
372           NaN
373           NaN
374           NaN
375           NaN
376           NaN
377           NaN
378           NaN
379           NaN
380           NaN
381           NaN
382           NaN
383           NaN
384           NaN
385           NaN
386           NaN
387           NaN
388           NaN
389           NaN
390           NaN
391           NaN
392           NaN
393           NaN
394           NaN
395           NaN
396           NaN
397           NaN
398           NaN
399           NaN
400           NaN
401           NaN
402           NaN
403           NaN
404           NaN
405           NaN
406           NaN
407           NaN
408           NaN
409           NaN
410           NaN
411           NaN
412           NaN
413           NaN
414           NaN
415           NaN
416           NaN
417           NaN
418           NaN
419           NaN
420           NaN
421           NaN
422           NaN
423           NaN
424           NaN
425           NaN
426           NaN
427           NaN
428           NaN
429           NaN
430           NaN
431           NaN
432           NaN
433           NaN
434           NaN
435           NaN
436           NaN
437           NaN
438           NaN
439           NaN
440           NaN
441           NaN
442           NaN
443           NaN
444           NaN
445           NaN
446           NaN
447           NaN
448           NaN
449           NaN
450           NaN
451           NaN
452           NaN
453           NaN
454           NaN
455           NaN
456           NaN
457           NaN
458           NaN
459           NaN
460           NaN
461           NaN
462           NaN
463           NaN
464           NaN
465           NaN
466           NaN
467           NaN
468           NaN
469           NaN
470           NaN
471           NaN
472           NaN
473           NaN
474           NaN
475           NaN
476           NaN
477           NaN
478           NaN
479           NaN
480           NaN
481           NaN
482           NaN
483           NaN
484           NaN
485           NaN
486           NaN
487           NaN
488           NaN
489           NaN
490           NaN
491           NaN
492           NaN
493           NaN
494           NaN
495           NaN
496           NaN
497           NaN
498           NaN
499           NaN
500           NaN
501           NaN
502           NaN
503           NaN
504           NaN
505           NaN
506           NaN
507           NaN
508           NaN
509           NaN
510           NaN
511           NaN
512           NaN
513           NaN
514           NaN
515        -0.847
516        -2.603
517         0.093
518        -0.981
519        -2.122
520        -3.314
521        -4.234
522        -3.381
523        -1.151
524        -6.284
525       -21.159
526       -18.862
527       -17.784
528       -17.291
529       -17.320
530       -16.294
531       -13.490
532       -12.264
533       -12.045
534        -6.863
535        -7.242
536        -5.089
537        -3.389
538         0.967
539         1.036
540         2.917
541         2.667
542        -0.598
543        -0.104
544        -0.995
545         0.827
546         0.281
547        -0.742
548        -1.656
549           NaN
550           NaN
551           NaN
552           NaN
553           NaN
554           NaN
555           NaN
556           NaN
557           NaN
558           NaN
559           NaN
560           NaN
561           NaN
562           NaN
563           NaN
564           NaN
565           NaN
566           NaN
567           NaN
568           NaN
569           NaN
570           NaN
571           NaN
572           NaN
573           NaN
574           NaN
575           NaN
576           NaN
577           NaN
578           NaN
579           NaN
580           NaN
581           NaN
582           NaN
583           NaN
584           NaN
585           NaN
586           NaN
587           NaN
588           NaN
589           NaN
590           NaN
591           NaN
592           NaN
593           NaN
594           NaN
595           NaN
596           NaN
597           NaN
598           NaN
599           NaN
600           NaN
601           NaN
602           NaN
603           NaN
604           NaN
605           NaN
606           NaN
607           NaN
608           NaN
609           NaN
610           NaN
611           NaN
612           NaN
613           NaN
614           NaN
615           NaN
616           NaN
617           NaN
618           NaN
619           NaN
620           NaN
621           NaN
622           NaN
623           NaN
624           NaN
625           NaN
626           NaN
627           NaN
628           NaN
629           NaN
630           NaN
631           NaN
632           NaN
633           NaN
634           NaN
635           NaN
636           NaN
637           NaN
638           NaN
639           NaN
640           NaN
641           NaN
642           NaN
643           NaN
644           NaN
645           NaN
646           NaN
647           NaN
648           NaN
649           NaN
650           NaN
651           NaN
652           NaN
653           NaN
654           NaN
655           NaN
656           NaN
657           NaN
658           NaN
659           NaN
660           NaN
661           NaN
662           NaN
663           NaN
664           NaN
665           NaN
666           NaN
667           NaN
668           NaN
669           NaN
670           NaN
671           NaN
672           NaN
673           NaN
674           NaN
675           NaN
676           NaN
677           NaN
678           NaN
679           NaN
680           NaN
681           NaN
682           NaN
683           NaN
684           NaN
685           NaN
686           NaN
687           NaN
688           NaN
689           NaN
690           NaN
691           NaN
692           NaN
693           NaN
694           NaN
695           NaN
696           NaN
697           NaN
698           NaN
699           NaN
700           NaN
701           NaN
702           NaN
703           NaN
704           NaN
705           NaN
706           NaN
707           NaN
708           NaN
709           NaN
710           NaN
711           NaN
712           NaN
713           NaN
714           NaN
715           NaN
716           NaN
717           NaN
718           NaN
719           NaN
720           NaN
721           NaN
722           NaN
723           NaN
724           NaN
725           NaN
726           NaN
727           NaN
728           NaN
729           NaN
730           NaN
731           NaN
732           NaN
733           NaN
734           NaN
735           NaN
736           NaN
737           NaN
738           NaN
739           NaN
740           NaN
741           NaN
742           NaN
743           NaN
744           NaN
745           NaN
746           NaN
747           NaN
748           NaN
749           NaN
750           NaN
751           NaN
752           NaN
753           NaN
754           NaN
755           NaN
756           NaN
757           NaN
758           NaN
759           NaN
760           NaN
761           NaN
762           NaN
763           NaN
764           NaN
765           NaN
766           NaN
767           NaN
768           NaN
769           NaN
770           NaN
771           NaN
772           NaN
773           NaN
774           NaN
775           NaN
776           NaN
777           NaN
778           NaN
779           NaN
780           NaN
781           NaN
782           NaN
783           NaN
784           NaN
785           NaN
786           NaN
787           NaN
788           NaN
789           NaN
790           NaN
791           NaN
792           NaN
793           NaN
794           NaN
795           NaN
796           NaN
797           NaN
798           NaN
799           NaN
800           NaN
801           NaN
802           NaN
803           NaN
804           NaN
805           NaN
806           NaN
807           NaN
808           NaN
809           NaN
810           NaN
811           NaN
812           NaN
813           NaN
814           NaN
815           NaN
816           NaN
817           NaN
818           NaN
819           NaN
820           NaN
821           NaN
822           NaN
823           NaN
824           NaN
825           NaN
826           NaN
827           NaN
828           NaN
829           NaN
830           NaN
831           NaN
832           NaN
833           NaN
834           NaN
835           NaN
836           NaN
837           NaN
838           NaN
839           NaN
840           NaN
841           NaN
842           NaN
843           NaN
844           NaN
845           NaN
846           NaN
847           NaN
848           NaN
849           NaN
850           NaN
851           NaN
852           NaN
853           NaN
854           NaN
855           NaN
856           NaN
857           NaN
858           NaN
859           NaN
860           NaN
861           NaN
862           NaN
863           NaN
864           NaN
865         0.958
866         7.595
867        16.202
868        14.406
869        22.951
870        20.778
871        43.489
872        42.070
873        38.666
874        24.167
875        30.911
876        37.760
877        31.312
878        38.126
879        32.376
880        37.343
881        49.174
882        51.313
883        48.978
884        54.276
885        36.598
886        34.949
887        33.280
888        21.880
889         7.060
890        25.082
891        28.401
892        14.211
893        20.578
894        21.864
895        22.782
896        20.655
897        26.412
898        21.838
899           NaN
900           NaN
901           NaN
902           NaN
903           NaN
904           NaN
905           NaN
906           NaN
907           NaN
908           NaN
909           NaN
910           NaN
911           NaN
912           NaN
913           NaN
914           NaN
915           NaN
916           NaN
917           NaN
918           NaN
919           NaN
920           NaN
921           NaN
922           NaN
923           NaN
924           NaN
925           NaN
926           NaN
927           NaN
928           NaN
929           NaN
930           NaN
931           NaN
932           NaN
933           NaN
934           NaN
935           NaN
936           NaN
937           NaN
938           NaN
939           NaN
940           NaN
941           NaN
942           NaN
943           NaN
944           NaN
945           NaN
946           NaN
947           NaN
948           NaN
949           NaN
950           NaN
951           NaN
952           NaN
953           NaN
954           NaN
955           NaN
956           NaN
957           NaN
958           NaN
959           NaN
960           NaN
961           NaN
962           NaN
963           NaN
964           NaN
965           NaN
966           NaN
967           NaN
968           NaN
969           NaN
970           NaN
971           NaN
972           NaN
973           NaN
974           NaN
975           NaN
976           NaN
977           NaN
978           NaN
979           NaN
980           NaN
981           NaN
982           NaN
983           NaN
984           NaN
985           NaN
986           NaN
987           NaN
988           NaN
989           NaN
990           NaN
991           NaN
992           NaN
993           NaN
994           NaN
995           NaN
996           NaN
997           NaN
998           NaN
999           NaN
1000          NaN
1001          NaN
1002          NaN
1003          NaN
1004          NaN
1005          NaN
1006          NaN
1007          NaN
1008          NaN
1009          NaN
1010          NaN
1011          NaN
1012          NaN
1013          NaN
1014          NaN
1015          NaN
1016          NaN
1017          NaN
1018          NaN
1019          NaN
1020          NaN
1021          NaN
1022          NaN
1023          NaN
1024          NaN
1025          NaN
1026          NaN
1027          NaN
1028          NaN
1029          NaN
1030          NaN
1031          NaN
1032          NaN
1033          NaN
1034          NaN
1035          NaN
1036          NaN
1037          NaN
1038          NaN
1039          NaN
1040          NaN
1041          NaN
1042          NaN
1043          NaN
1044          NaN
1045          NaN
1046          NaN
1047          NaN
1048          NaN
1049          NaN
1050          NaN
1051          NaN
1052          NaN
1053          NaN
1054          NaN
1055          NaN
1056          NaN
1057          NaN
1058          NaN
1059          NaN
1060          NaN
1061          NaN
1062          NaN
1063          NaN
1064          NaN
1065          NaN
1066          NaN
1067          NaN
1068          NaN
1069          NaN
1070          NaN
1071          NaN
1072          NaN
1073          NaN
1074          NaN
1075          NaN
1076          NaN
1077          NaN
1078          NaN
1079          NaN
1080          NaN
1081          NaN
1082          NaN
1083          NaN
1084          NaN
1085          NaN
1086          NaN
1087          NaN
1088          NaN
1089          NaN
1090          NaN
1091          NaN
1092          NaN
1093          NaN
1094          NaN
1095          NaN
1096          NaN
1097          NaN
1098          NaN
1099          NaN
1100          NaN
1101          NaN
1102          NaN
1103          NaN
1104          NaN
1105          NaN
1106          NaN
1107          NaN
1108          NaN
1109          NaN
1110          NaN

## Data Preprocessing

### Steps in the data preprocessing pipeline
1. Remove years below 1950.
2. Removing columns with more than 50% missing.
3. Impute missing values.
4. Removing outliers.
5. Separate continents from countries in their own datasets.

In [194]:
# Preprocessing pipeline
def preprocessing_pipeline(data):
    # Making a copy of the original dataset
    data = data.copy()

    # 1. Removing years below 1950
    data = data[data['year'] >= 1950]

    # 2. Removing columns with more than 50% missing
    data = data.loc[:, data.isnull().mean() <= 0.5]

    # Replace all values of 0 with NaN
    data = data.replace(0, np.nan)
    
    # 3. Imputing missing values
    # 3.1. Get the descriptive statistics dataframe
    desc = data.describe()

    # 3.2. Isolate the rows for Q1, Q2, and Q3
    quartiles = desc.loc[["25%", "50%", "75%"]]

    # 3.3. Find which row name ("25%", "50%", or "75%") holds the largest value per column
    largest_quartile = quartiles.idxmax(axis=0)
    
    # 3.4. Loop through columns and apply the corresponding imputation
    for col in df.columns:
        # Skip columns that aren't numeric (not present in df.describe)
        if col not in largest_quartile.index:
            continue

        # Rule: Use mean if Q2 ("50%") is the largest
        if largest_quartile[col] == "50%":
            fill_value = desc.loc["mean", col]

        # Rule: Use median if Q1 ("25%") or Q3 ("75%") is the largest
        else:
            fill_value = desc.loc["50%", col]

        # Apply the imputation to the column
        data[col] = data[col].fillna(fill_value)

    # 5. Separating continents from countries in their own datasets.
    # List of all continents
    continent = [
        'Africa',
        'Africa (GCP)'
        'Asia',
        'Asia (GCP)',
        'Asia (excl. China and India)',
        'Europe',
        'Europe (GCP)',
        'Europe (excl. EU-27)',
        'Europe (excl. EU-28)',
        'European Union (27)',
        'European Union (28)',
        'North America',
        'Central America (GCP)',
        'North America',
        'North America (GCP)',
        'North America (excl. USA)',
        'South America',
        'South America (GCP)',
        'Oceania',
        'Oceania (GCP)'
        ]

    # Actually separating the continents
    data_continent = data[data['country'].isin(continent)]

    # Returning the dataset
    return data, data_continent

df_cleaned, df_continent = preprocessing_pipeline(df)
df_cleaned.isnull().sum()
#df_cleaned.head(50)

country                                         0
year                                            0
iso_code                                     2634
population                                      0
gdp                                             0
cement_co2                                      0
cement_co2_per_capita                           0
co2                                             0
co2_growth_abs                                  0
co2_growth_prct                                 0
co2_including_luc                               0
co2_including_luc_growth_abs                    0
co2_including_luc_growth_prct                   0
co2_including_luc_per_capita                    0
co2_including_luc_per_gdp                       0
co2_including_luc_per_unit_energy               0
co2_per_capita                                  0
co2_per_gdp                                     0
co2_per_unit_energy                             0
coal_co2                                        0
coal_co2_per_capita                             0
cumulative_cement_co2                           0
cumulative_co2                                  0
cumulative_co2_including_luc                    0
cumulative_coal_co2                             0
cumulative_flaring_co2                          0
cumulative_luc_co2                              0
cumulative_oil_co2                              0
energy_per_capita                               0
flaring_co2                                     0
flaring_co2_per_capita                          0
ghg_excluding_lucf_per_capita                   0
ghg_per_capita                                  0
land_use_change_co2                             0
land_use_change_co2_per_capita                  0
methane                                         0
methane_per_capita                              0
nitrous_oxide                                   0
nitrous_oxide_per_capita                        0
oil_co2                                         0
oil_co2_per_capita                              0
primary_energy_consumption                      0
share_global_cement_co2                         0
share_global_co2                                0
share_global_co2_including_luc                  0
share_global_coal_co2                           0
share_global_cumulative_cement_co2              0
share_global_cumulative_co2                     0
share_global_cumulative_co2_including_luc       0
share_global_cumulative_coal_co2                0
share_global_cumulative_flaring_co2             0
share_global_cumulative_luc_co2                 0
share_global_cumulative_oil_co2                 0
share_global_flaring_co2                        0
share_global_luc_co2                            0
share_global_oil_co2                            0
share_of_temperature_change_from_ghg            0
temperature_change_from_ch4                     0
temperature_change_from_co2                     0
temperature_change_from_ghg                     0
temperature_change_from_n2o                     0
total_ghg                                       0
total_ghg_excluding_lucf                        0
dtype: int64

## Modeling

### Base Model

## Evaluation

## Deployment